# Generated by Django 4.0.4 on 2022-05-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_Directory_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcard',
            name='courseData',
            field=models.ManyToManyField(to='students_Directory_page.course'),
        ),
    ]
