# Generated by Django 4.0.4 on 2022-05-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_Directory_page', '0002_studentcard_coursedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcard',
            name='courseData',
        ),
    ]
