# Generated by Django 4.0.4 on 2022-05-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_Directory_page', '0003_remove_studentcard_coursedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='studentKey',
        ),
        migrations.AddField(
            model_name='course',
            name='studentKey',
            field=models.ManyToManyField(to='students_Directory_page.studentcard'),
        ),
    ]
